export enum BuildPlatform {
  Standalone = "standalone",
  Windows32 = "Win",
  Windows64 = "Win64",
  OSXUniversal = "OSXUniversal",
  Linux = "Linux",
  Linux64 = "Linux64",
  LinuxUniversal = "LinuxUniversal",
  IOS = "iOS",
  Android = "Android",
  Web = "Web",
  WebStreamed = "WebStreamed",
  WebGL = "WebGL",
  XboxOne = "XboxOne",
  PS4 = "PS4",
  WindowsStoreApps = "WindowsStoreApps",
  Switch = "Switch",
  N3DS = "N3DS",
  TVOS = "tvOS",
  VisionOS = "visionos",
}
